name: listing s3 buckets  

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

# permission can be added at job level or workflow level
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  listing_buckets:
    runs-on: ubuntu-latest
    steps:
      - name: setup aws credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.IAM_ROLE }} 
          aws-region: ${{ secrets.AWS_REGION }}

      - name: list s3 buckets
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: 
            echo "Listing S3 buckets in region $AWS_REGION"
            aws s3 ls   
