name: Create an s3 bucket

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

# permission can be added at job level or workflow level
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  creating_bucket:
    runs-on: ubuntu-latest
    steps:
      - name : checkout repo
        uses: actions/checkout@v7

      - name: setup aws credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.IAM_ROLE }} 
          aws-region: ${{ secrets.AWS_REGION }}

      - name: install terraform
        uses: hashicorp/setup-terraform@v4

      - name: terraform init
        run: terraform init
        working-directory: terraform

      - name: terraform plan
        env:
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
        run: |
          terraform plan \
              -var "bucketname=${BUCKET_NAME}"
        working-directory: terraform

      - name: terraform apply
        env:
          TF_VAR_bucket_name: ${{ secrets.BUCKET_NAME }}
        run: terraform apply -auto-approve
        working-directory: terraform
